---
version: '3.6'

x-besu-def:
  &besu-def
  restart: "on-failure"
  image: hyperledger/besu:${BESU_VERSION:-latest}
  env_file:
    - ./network/config/besu/.env
  entrypoint:
    - /bin/bash
    - -c
    - |

      cp "/config/${BESU_CONS_ALGO:-QBFT}genesis.json" /config/genesis.json

      /opt/besu/bin/besu \
      --config-file=/config/config.toml \
      --p2p-host=$$(hostname -i) \
      --rpc-http-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PERM,${BESU_CONS_ALGO:-QBFT} \
      --rpc-ws-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PERM,${BESU_CONS_ALGO:-QBFT} ;









x-ethsignerProxy-def:
  &ethsignerProxy-def
  image: consensys/ethsigner:${ETHSIGNER_VERSION:-latest}
  command: [
      "--chain-id=1337",
      "--http-listen-host=0.0.0.0",
      "--downstream-http-port=8545",
      "--downstream-http-host=rpcnode",
      "file-based-signer",
      "-k",
      "/opt/ethsigner/keyfile",
      "-p",
      "/opt/ethsigner/passwordfile"
  ]
  ports:
    - 8545

services:

  validator1:
    << : *besu-def
    ports:
      - 21001:8545/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator1,service.version=${BESU_VERSION:-latest}
    labels:
      - "consensus=besu"
    volumes:
      - ./network/config/besu/:/config
      - ./network/config/nodes/validator1:/opt/besu/keys
      - ./network/logs/besu:/tmp/besu
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.11

  validator2:
    << : *besu-def
    ports:
      - 21002:8545/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator2,service.version=${BESU_VERSION:-latest}
    labels:
      - "consensus=besu"
    volumes:
      - ./network/config/besu/:/config
      - ./network/config/nodes/validator2:/opt/besu/keys
      - ./network/logs/besu:/tmp/besu
    depends_on:
      - validator1
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.12

  validator3:
    << : *besu-def
    ports:
      - 21003:8545/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator3,service.version=${BESU_VERSION:-latest}
    labels:
      - "consensus=besu"
    volumes:
      - ./network/config/besu/:/config
      - ./network/config/nodes/validator3:/opt/besu/keys
      - ./network/logs/besu:/tmp/besu
    depends_on:
      - validator1
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.13

  validator4:
    << : *besu-def
    ports:
      - 21004:8545/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator4,service.version=${BESU_VERSION:-latest}
    labels:
      - "consensus=besu"
    volumes:
      - ./network/config/besu/:/config
      - ./network/config/nodes/validator4:/opt/besu/keys
      - ./network/logs/besu:/tmp/besu
    depends_on:
      - validator1
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.14

  rpcnode:
    << : *besu-def
    container_name: rpcnode
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=rpcnode,service.version=${BESU_VERSION:-latest}
    volumes:
      - ./network/config/besu/:/config
      - ./network/config/nodes/rpcnode:/opt/besu/keys
      - ./network/logs/besu:/tmp/besu
    depends_on:
      - validator1
    ports:
      - 8545:8545/tcp
      - 8546:8546/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.15

  ethsignerProxy:
    << : *ethsignerProxy-def
    volumes:
      - ./network/config/ethsigner/password:/opt/ethsigner/passwordfile
      - ./network/config/ethsigner/key:/opt/ethsigner/keyfile
    depends_on:
      - validator1
      - rpcnode
    ports:
      - 18545:8545/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.40











  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./network/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.32

  grafana:
    image: "grafana/grafana"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_USERS_VIEWERS_CAN_EDIT=true
    volumes:
      - ./network/config/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.33

  loki:
    image: "grafana/loki"
    volumes:
      - ./network/infra/loki/loki.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100:3100/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.34

  promtail:
    image: "grafana/promtail"
    volumes:
      - ./network/logs:/var/log
      - ./network/infra/promtail/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.35






volumes:
  public-keys:
  prometheus:
  grafana:
  ethlogger:
  blockscoutpostgres:

networks:
  quorum-dev-quickstart:
    name: quorum-dev-quickstart
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24
