---
version: '3.6'

x-besu-def:
  &besu-def
  restart: "on-failure"
  image: hyperledger/besu:${BESU_VERSION:-latest}
  env_file:
    - ./config/besu/.env
  entrypoint:
    - /bin/bash
    - -c
    - |

      cp "/config/${BESU_CONS_ALGO:-QBFT}genesis.json" /config/genesis.json

      /opt/besu/bin/besu \
      --config-file=/config/config.toml \
      --p2p-host=$$(hostname -i) \
      --rpc-http-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,${BESU_CONS_ALGO:-QBFT} \
      --rpc-ws-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,${BESU_CONS_ALGO:-QBFT} ;


x-tessera-def:
  &tessera-def
  build:
    context: config/tessera
    args:
      TESSERA_VERSION: ${TESSERA_VERSION:-latest}
  environment:
    TESSERA_MODE: orion
  expose:
    - 9000
    - 9080
    - 9101
  restart: "no"
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:9000/upcheck"]
    interval: 3s
    timeout: 3s
    retries: 20
    start_period: 5s







x-blockscout-ref:
  &blockscout-def
  image: consensys/blockscout:v4.1.5-beta
  container_name: blockscout
  restart: "no"
  environment:
    - PORT=4000
    - ECTO_USE_SSL=false
    - DATABASE_URL=postgresql://postgres:postgres@blockscoutpostgres:5432/postgres?ssl=false
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - NETWORK=quickstart
    - NETWORK=Dev Quickstart
    - SUBNETWORK=Quorum
    - CHAIN_ID=1337
    - COIN=ETH
    - ETHEREUM_JSONRPC_VARIANT=besu
    - ETHEREUM_JSONRPC_TRANSPORT=http
    - ETHEREUM_JSONRPC_HTTP_URL=http://rpcnode:8545
    - ETHEREUM_JSONRPC_TRACE_URL=http://rpcnode:8545
    - ETHEREUM_JSONRPC_WS_URL=ws://rpcnode:8546
  entrypoint:
    - /bin/sh
    - -c
    - |
      cd /opt/app/;
      echo $$MIX_ENV && mix do ecto.create, ecto.migrate; mix phx.server;
  depends_on:
    - blockscoutpostgres
  links:
    - blockscoutpostgres
  ports:
    - 26000:4000

x-blockscoutpostgres-ref:
  &blockscoutpostgres-def
  image: postgres:13.6-alpine
  restart: "on-failure"
  container_name: blockscoutpostgres
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_HOST_AUTH_METHOD=trust
  volumes:
    - blockscoutpostgres:/var/lib/postgresql/data
  ports:
    - 5432
  healthcheck:
    test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    interval: 5s
    timeout: 10s
    retries: 5





x-chainlensapi-ref:
  &chainlensapi-def
  image: web3labs/epirus-free-api:latest
  container_name: chainlensapi
  environment:
    - NODE_ENDPOINT=http://rpcnode:8545
    - MONGO_CLIENT_URI=mongodb://chainlensmongodb:27017
    - REINDEX_ENDPOINT=http://chainlensingestion/reindex/
    - MONGO_DB_NAME=epirus
    - MONGO_CREATE_INDICES=true
  depends_on:
    - chainlensmongodb

x-chainlensmongodb-ref:
  &chainlensmongodb-def
  image: mongo:5.0.8
  container_name: chainlensmongodb
  environment:
    - COMPOSE_HTTP_TIMEOUT=900
    - DOCKER_CLIENT_TIMEOUT=900
  entrypoint: mongod --bind_ip "0.0.0.0"

x-chainlensweb-ref:
  &chainlensweb-def
  image: web3labs/epirus-free-web:latest
  container_name: chainlensweb
  environment:
    - API_URL=/api
    - DISPLAY_NETWORK_TAB=disabled
  depends_on:
    - chainlensapi

x-chainlensingestion-ref:
  &chainlensingestion-def
  image: web3labs/epirus-free-ingestion:latest
  container_name: chainlensingestion
  environment:
    - NODE_ENDPOINT=http://rpcnode:8545
    - MONGO_CLIENT_URI=mongodb://chainlensmongodb:27017
    - MONGO_DB_NAME=epirus
  depends_on:
    - chainlensmongodb
    - chainlensweb

x-chainlensnginx-ref:
  &chainlensnginx-def
  image: nginx:latest
  container_name: chainlensnginx
  volumes:
    - ./chainlens/nginx.conf:/etc/nginx/nginx.conf
    - ./chainlens/5xx.html:/www/error_pages/5xx.html
  ports:
    - 8081:80
  depends_on:
    - chainlensapi
    - chainlensweb



x-ethsignerProxy-def:
  &ethsignerProxy-def
  image: consensys/ethsigner:${ETHSIGNER_VERSION:-latest}
  command: [
    "--chain-id=1337",
    "--http-listen-host=0.0.0.0",
    "--downstream-http-port=8545",
    "--downstream-http-host=rpcnode",
    "file-based-signer",
    "-k",
    "/opt/ethsigner/keyfile",
    "-p",
    "/opt/ethsigner/passwordfile"
  ]
  ports:
    - 8545

services:

  validator1:
    << : *besu-def
    ports:
      - 21001:8545/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator1,service.version=${BESU_VERSION:-latest}
    labels:
      - "consensus=besu"
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/validator1:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.11

  validator2:
    << : *besu-def
    ports:
      - 21002:8545/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator2,service.version=${BESU_VERSION:-latest}
    labels:
      - "consensus=besu"
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/validator2:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.12

  validator3:
    << : *besu-def
    ports:
      - 21003:8545/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator3,service.version=${BESU_VERSION:-latest}
    labels:
      - "consensus=besu"
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/validator3:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.13

  validator4:
    << : *besu-def
    ports:
      - 21004:8545/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator4,service.version=${BESU_VERSION:-latest}
    labels:
      - "consensus=besu"
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/validator4:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.14

  rpcnode:
    << : *besu-def
    container_name: rpcnode
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=rpcnode,service.version=${BESU_VERSION:-latest}
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/rpcnode:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
    ports:
      - 8545:8545/tcp
      - 8546:8546/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.15

  ethsignerProxy:
    << : *ethsignerProxy-def
    volumes:
      - ./config/ethsigner/password:/opt/ethsigner/passwordfile
      - ./config/ethsigner/key:/opt/ethsigner/keyfile
    depends_on:
      - validator1
      - rpcnode
    ports:
      - 18545:8545/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.40


  member1tessera:
    << : *tessera-def
    ports:
      - 9081:9080
    volumes:
      - ./config/nodes/member1:/config/keys
      - ./logs/tessera:/var/log/tessera/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.26

  member1besu:
    << : *besu-def
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=member1besu,service.version=${BESU_VERSION:-latest}
      - NODE_ID=6
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/config/config.toml \
        --p2p-host=$$(hostname -i) \
        --privacy-enabled \
        --privacy-url=http://member1tessera:9101 \
        --privacy-public-key-file=/opt/besu/keys/tm.pub \
        --privacy-onchain-groups-enabled=${PRIVACY_ONCHAIN_GROUPS_ENABLED:-false} \
        --rpc-http-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,${BESU_CONS_ALGO:-QBFT} \
        --rpc-ws-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,${BESU_CONS_ALGO:-QBFT} ;
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/member1:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
      - member1tessera
    ports:
      - 20000:8545/tcp
      - 20001:8546/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.16

  member2tessera:
    << : *tessera-def
    ports:
      - 9082:9080
    volumes:
      - ./config/nodes/member2:/config/keys
      - ./logs/tessera:/var/log/tessera/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.27

  member2besu:
    << : *besu-def
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=member2besu,service.version=${BESU_VERSION:-latest}
      - NODE_ID=7
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/config/config.toml \
        --p2p-host=$$(hostname -i) \
        --privacy-enabled \
        --privacy-url=http://member2tessera:9101 \
        --privacy-public-key-file=/opt/besu/keys/tm.pub \
        --privacy-onchain-groups-enabled=${PRIVACY_ONCHAIN_GROUPS_ENABLED:-false} \
        --rpc-http-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,${BESU_CONS_ALGO:-QBFT} \
        --rpc-ws-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,${BESU_CONS_ALGO:-QBFT} ;
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/member2:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
      - member2tessera
    ports:
      - 20002:8545/tcp
      - 20003:8546/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.17

  member3tessera:
    << : *tessera-def
    ports:
      - 9083:9080
    volumes:
      - ./config/nodes/member3:/config/keys
      - ./logs/tessera:/var/log/tessera/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.28

  member3besu:
    << : *besu-def
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=member3besu,service.version=${BESU_VERSION:-latest}
      - NODE_ID=8
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/config/config.toml \
        --p2p-host=$$(hostname -i) \
        --privacy-enabled \
        --privacy-url=http://member3tessera:9101 \
        --privacy-public-key-file=/opt/besu/keys/tm.pub \
        --privacy-onchain-groups-enabled=${PRIVACY_ONCHAIN_GROUPS_ENABLED:-false} \
        --rpc-http-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,${BESU_CONS_ALGO:-QBFT} \
        --rpc-ws-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,${BESU_CONS_ALGO:-QBFT} ;
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/member3:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
      - member3tessera
    ports:
      - 20004:8545/tcp
      - 20005:8546/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.18



  explorer:
    image: consensys/quorum-explorer:${QUORUM_EXPLORER_VERSION:-latest}
    volumes:
      - ./quorum-explorer/config.json:/app/config.json
      - ./quorum-explorer/env:/app/.env.production
    depends_on:
      - rpcnode
    ports:
      - 25000:25000/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.31



  blockscout:
    << : *blockscout-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.51

  blockscoutpostgres:
    << : *blockscoutpostgres-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.52




  chainlensapi:
    <<: *chainlensapi-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.53

  chainlensmongodb:
    <<: *chainlensmongodb-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.54

  chainlensingestion:
    <<: *chainlensingestion-def
    depends_on:
      - rpcnode
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.55

  chainlensweb:
    <<: *chainlensweb-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.56

  chainlensnginx:
    <<: *chainlensnginx-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.57




  prometheus:
    image: "prom/prometheus:v2.46.0"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.32

  grafana:
    image: "grafana/grafana:10.1.0"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_USERS_VIEWERS_CAN_EDIT=true
    volumes:
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.33

  loki:
    image: "grafana/loki:2.8.4"
    volumes:
      - ./loki/loki.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100:3100/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.34

  promtail:
    image: "grafana/promtail:2.8.4"
    volumes:
      - ./logs:/var/log
      - ./promtail/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.35






volumes:
  public-keys:
  prometheus:
  grafana:
  splunk:
  ethlogger:
  blockscoutpostgres:

networks:
  quorum-dev-quickstart:
    name: quorum-dev-quickstart
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24
