---
- name: Ensure directory for ssh settings exists
  file:
    path: "{{ ssh_dir }}"
    state: directory

- name: Create key-pair
  expect:
    command: "ssh-keygen -f {{ ssh_dir }}/key"
    creates: "{{ ssh_dir }}/key"
    responses:
      passphrase: ""

- name: Upload public key
  ec2_key:
    name: "{{ aws_keyname }}"
    region: "{{ item }}"
    key_material: "{{ lookup('file', '{{ ssh_dir }}/key.pub') }}"
  with_items: "{{ aws_regions }}"

- name: Create AWS security group
  ec2_group:
    name: "{{ aws_sgroup }}"
    region: "{{ item }}"
    description: "[{{ aws_tag_project }}] Security group for {{ aws_tag_role }} in {{ aws_tag_namespace }}"
    tags:
      Name: "{{ aws_tag_sgroup_name }}"
      Project: "{{ aws_tag_project }}"
      Namespace: "{{ aws_tag_namespace }}"
      Role: "{{ aws_tag_role }}"
    rules:
      - proto: all
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  with_items: "{{ aws_regions }}"
