---
- name: Check that required variables are specified
  assert:
    that:
      - lookup('vars', item, default='')
    msg: "{{ lookup('vars', item, default='undefined')|string }}"
  loop:
    - aws_project_name
    - aws_project_name_short
    - aws_regions
    - aws_ec2_type
    - aws_tag_project
    - aws_tag_namespace
    - aws_tag_role
    - aws_keyname
    - aws_sgroup
    - aws_tag_sgroup_name
    - aws_inventory_dir
    - aws_inventory_file
    - group_name

- name: Check that instance_count has acceptable values
  assert:
    that:
      - instance_count >= 0
    msg: "{{ instance_count|string }}"
