- hosts: pool
  gather_facts: no

  tasks:
  - name: Save journalctl log
    shell: "journalctl > /tmp/jctl"

  - name: Compress journalctl log
    shell: "xz -f /tmp/jctl"

  - name: Fetch journalctl log
    fetch:
      src: "/tmp/jctl.xz"
      dest: "./logs/jctl/{{ inventory_hostname }}.jctl.xz"
      flat: yes

  - name: Delete journalctl log
    file:
      path: "/tmp/jctl.xz"
      state: absent

  - name: Fetch node logs
    synchronize:
      src: /var/log/indy/sandbox/
      dest: ./logs
      mode: pull
