name: Triggered by Version Bump Release PR

on:
  pull_request:
    paths:
      - '!**'
      - "indy_node/__version__.json"
  workflow_dispatch:

jobs:
  release-infos:
    name: infos
    runs-on: ubuntu-latest
    outputs:
      isVersionBump: ${{ steps.get-release-info.outputs.isVersionBump }}
      isPreRelease: ${{ steps.get-release-info.outputs.isRC }}
      CACHE_KEY_BUILD: ${{ steps.workflow-setup.outputs.CACHE_KEY_BUILD }}
      UBUNTU_VERSION: ${{ steps.workflow-setup.outputs.UBUNTU_VERSION }}
      # Expose the lowercase version of the GitHub repository name
      # to all subsequent jobs that reference image repositories
      # as the push and pull operations require the URL of the repository
      # to be in lowercase.
      GITHUB_REPOSITORY_NAME: ${{ steps.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}
      distribution: ${{ steps.workflow-setup.outputs.distribution }}
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: get-release-info
        id: get-release-info
        uses: hyperledger/indy-shared-gha/.github/actions/get-release-info@v2
        with:
          versionString: "${{ github.event.pull_request.body }}"
      - name: workflow-setup
        id: workflow-setup
        uses: hyperledger/indy-shared-gha/.github/actions/workflow-setup@v2

  lint:
    name: Lint
    needs: [release-infos]
    if: needs.release-infos.outputs.isVersionBump == 'true'
    uses: hyperledger/indy-shared-gha/.github/workflows/lint.yaml@v2

  build-docker-image:
    name: Create Builder Image
    needs: [release-infos, lint]
    if: needs.release-infos.outputs.isVersionBump == 'true'
    uses: hyperledger/indy-shared-gha/.github/workflows/buildimage.yaml@v2
    with:
      CACHE_KEY_BUILD: ${{ needs.release-infos.outputs.CACHE_KEY_BUILD }}
      DOCKER_IMAGE: ghcr.io/${{ needs.release-infos.outputs.GITHUB_REPOSITORY_NAME }}/node-build
      UBUNTU_VERSION: ${{ needs.release-infos.outputs.UBUNTU_VERSION }}

  build_packages:
    name: Build Packages
    needs: [release-infos, build-docker-image]
    if: needs.release-infos.outputs.isVersionBump == 'true'
    uses: hyperledger/indy-shared-gha/.github/workflows/buildpackages.yaml@v2
    with:
      DOCKER_IMAGE: ghcr.io/${{ needs.release-infos.outputs.GITHUB_REPOSITORY_NAME }}/node-build:${{ needs.release-infos.outputs.UBUNTU_VERSION }}
      UBUNTU_VERSION: ${{ needs.release-infos.outputs.UBUNTU_VERSION }}
      isDev: 'false'
      isRC: '${{ needs.release-infos.outputs.isPreRelease }}'
      moduleName: indy_node

  indy_node_tests:
    name: Indy Node Tests
    needs: [release-infos, build_packages]
    if: needs.release-infos.outputs.isVersionBump == 'true'
    uses: ./.github/workflows/reuseable_test.yaml
    with:
      GITHUB_REPOSITORY_NAME: ${{ needs.release-infos.outputs.GITHUB_REPOSITORY_NAME }}
      UBUNTU_VERSION: ${{ needs.release-infos.outputs.UBUNTU_VERSION }}

  call-indy-test-automation:
    name: Indy-Test-Automation
    needs: [build_packages]
    uses: hyperledger/indy-test-automation/.github/workflows/callable_test-automation-node.yaml@v0.11
    with:
      ubuntuVersion: "ubuntu-2004"
      libIndyVersion: "1.15.0~1625-bionic"
      includePaymentTests: false
      testAutomationBranch: "v0.11"
      debName: "indy-node*.deb"
      packageName: "indy_node-deb"

  statusCheck:
    name: statusCheck
    runs-on: ubuntu-latest
    needs: [indy_node_tests, call-indy-test-automation]
    steps:
      - run: 'echo "Just a status Check (Always true, when executed) for branch protection rules(blocks merging while test are running and if tests fail)." '