---
# General
aws_project_name: Indy-PA
aws_group_name: defaults

  # Namespace parameters
aws_namespace_name: "{{ namespace_name | d(inventory_dir, true) | d('test', true) | basename }}"
aws_build_dir: "{{ namespace_dir | d(inventory_dir, true) | d(aws_namespace_name, true) }}"

  # Inventory parameters
aws_inventory_dir: "{{ inventory_dir | d(aws_build_dir ~ '/inventory', true) }}"
aws_inventory_file: "{{ aws_inventory_dir }}/{{ aws_group_name }}.yml"
aws_base_group: "{{ aws_namespace_name }}"

# Provision parameters

  # List of all potential regions to use
  # (for reference mostly)
aws_regions_all:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - sa-east-1  # !!! be aware: expensive
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2

  # List of regions to use
  # (the cheapest ones)
aws_regions:
  - us-east-1
  - us-east-2
  - us-west-2

aws_instance_count: 4

aws_ec2_type: t2.micro
aws_ec2_market_spot: true
aws_ec2_spot_max_price: null
aws_ebs_volume_size: 16
aws_ebs_volume_type: gp2

  # Resource tags and names
aws_tag_project: "{{ aws_project_name }}"
aws_tag_namespace: "{{ aws_namespace_name }}"
aws_tag_group: "{{ aws_group_name }}"
aws_add_tags: {} # additional tags

aws_resource_common_name: "{{ [aws_project_name, aws_tag_namespace, aws_group_name]|join('-')|lower }}"
aws_keyname: "{{ aws_resource_common_name }}"
aws_sgroup: "{{ aws_resource_common_name }}"
aws_tag_sgroup_name: "{{ aws_sgroup }}"