---
# General
aws_project_name: PoolAutomation
aws_project_name_short: PA

# Provision parameters
instance_count: 4

# AWS parameters
#   List of all potential regions to use
aws_regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2

#   EC2 instance type
aws_ec2_type: t2.micro

#   Resource tags and names
aws_tag_project: "{{ aws_project_name }}"
aws_tag_namespace: "{{ inventory_dir | default('test', true) | basename }}"
aws_tag_role: default
aws_add_tags: {} # additional tags

aws_resource_common_name: "{{ [aws_project_name_short, aws_tag_namespace, group_name]|join('-')|lower }}"
aws_keyname: "{{ aws_resource_common_name }}"
aws_sgroup: "{{ aws_resource_common_name }}"
aws_tag_sgroup_name: "{{ aws_sgroup }}"

# Inventory parameters
aws_inventory_dir: "{{ inventory_dir | default(aws_tag_namespace ~ '_' ~ group_name) }}"
aws_inventory_file: "{{ aws_inventory_dir }}/hosts"
group_name: "{{ aws_tag_role + 's' }}"
